name: DEV - Build & deploy
on:
 push:
   branches:
     - dev
jobs:
  build:
   name: Build
   runs-on: ubuntu-latest
   strategy:
     matrix:
       node-version: [14.x]
   steps:
   - name: Install Packages
     run: npm install   
   - name: Install Phaser
     run: npm install phaser 
   - name: Build projeto
     run: npm start
     
  deploy:
   name: Deploy
   needs: build
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/dev'
  
   steps:
   - name: Download artifact
     uses: actions/download-artifact@v2
     with:
       name: production-files
       path: ./build

   - name: Deploy to gh-pages
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{ secrets.GITHUB_TOKEN }}
       publish_dir: ./build
